# modules/evdi/system-manager.nix — the Arch/CachyOS implementation of nixgpu.evdi.
#
# Same three statements as the NixOS plane, expressed with the two mechanisms system-manager
# actually has. There is no `boot.*` here at all -- system-manager configures a running foreign
# distribution, it does not build that distribution's boot -- so both the module parameter and the
# load-at-boot instruction are ordinary files that systemd and modprobe already read:
#
#   /etc/modprobe.d/*.conf    -> read by modprobe every time the module is loaded, by anyone
#   /etc/modules-load.d/*.conf -> read by systemd-modules-load.service at boot
#
# ⚠ `replaceExisting = true` on both entries, and it is not boilerplate. If the destination path
# already exists on disk and an entry does not set it, system-manager SILENTLY DECLINES to write
# the file -- no error, no warning. On a box that has ever had a hand-written or pacman-shipped
# evdi conf at either path, the module would then apply cleanly and change nothing, which is the
# same silent no-op the `initial_device_count` default produces one layer down.
#
# ⚠ NOT RETROACTIVE. Writing /etc/modprobe.d changes nothing about an already-loaded module: evdi
# reads `initial_device_count` once, at `module_init()`. Changing `deviceCount` on a running box
# needs the module reloaded (`modprobe -r evdi && modprobe evdi`, with nothing holding a DRM node
# open) or a reboot -- the devices are permanent by design, and that cuts both ways.
#
# ── WHY THE nixarch WRITE BELOW IS UNCONDITIONAL, and why it cannot be otherwise ─────────────
#
# `nixarch.packages.aur` is an option nixarch DECLARES and this module SETS -- the same direction
# `nixgpu.toolchain`'s Arch plane already writes `nixarch.packages.pacman`. It is a write, not a
# cross-repo read, so it needs no flake input and no `probeFact`; what it does need is for
# nixarch's `packages` module to be composed on the host, and that requirement CANNOT be made
# conditional. Both obvious ways of trying were measured on this nixpkgs (2026-07-31), and both
# fail:
#
#   * `lib.mkIf false { nixarch.packages.aur = [ ]; }` -> still "The option `nixarch' does not
#     exist". `mkIf` is pushed DOWN into each attribute before option matching, so the attribute
#     name is offered to the module system either way; a false condition removes the value, not
#     the name.
#   * `lib.optionalAttrs (config ? nixarch) { ... }` -> infinite recursion. Deciding an attribute
#     NAME of this module's `config` from the merged option set requires that set, which requires
#     this module's config attribute names.
#
# So: importing this plane requires nixarch's `packages` module, `archPackage = null` included
# (which still emits an empty list). That is stated in the option's description rather than
# discovered from a module-system error. See modules/displaylink/system-manager.nix for the one
# genuine cross-repo READ in this pair, which does go through `probeFact`.
{ lib, config, ... }:
let
  cfg = config.nixgpu.evdi;
in
{
  config = lib.mkIf cfg.enable {
    environment.etc."modprobe.d/nixgpu-evdi.conf" = {
      replaceExisting = true;
      text = ''
        # Generated by nixgpu.evdi. Without this parameter evdi loads and creates NO DRM device:
        # initial_device_count defaults to 0 (module/evdi_params.c).
        options evdi initial_device_count=${toString cfg.deviceCount}
      '';
    };

    environment.etc."modules-load.d/nixgpu-evdi.conf" = {
      replaceExisting = true;
      text = ''
        # Generated by nixgpu.evdi.
        evdi
      '';
    };

    # See this file's header for why this is unconditional rather than guarded on nixarch being
    # composed. `lib.optionals` handles the null case, which is the container shape: the module is
    # loaded by a kernel pacman cannot see, so there is nothing here for it to install.
    nixarch.packages.aur = lib.optionals (cfg.archPackage != null) [ cfg.archPackage ];
  };
}
